apiVersion: v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: nginx:latest
        ports:
        - containerPort: 3000
